# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm test
      # - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_TOKEN
      # - run: npm install
      # - run: npm publish

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
        filters:
          tags:
            only: /.*/
    
